- name: catalogue
  hosts: catalogue
  become: yes
  tasks:
  - name: disabling old version of nodejs
    ansible.builtin.shell: dnf module disable nodejs -y ;dnf module enable nodejs:18 -y
  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present
  - name: add roboshop user
    ansible.builtin.user:
      name: roboshop
  - name: Recursively remove app directory
    ansible.builtin.file:
      path: /app
      state: absent
  - name: create a directory
    ansible.builtin.file:
      path: /app
      state: directory
  - name: download the application
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp
  - name: unzip application
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app 
      remote_src: yes
  - name: download dependencies
    ansible.builtin.command: npm install
    args:
      chdir: /app
  - name: ansible.builtin.copy catalogue service
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service
  - name: deamon realod and start
    ansible.builtin.systemd_service:
      daemon_reload: true
  - name: Copy mongodb repo
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongodb.repo

  - name: Install mongodb client
    ansible.builtin.package:
      name: mongodb-org-shell
      state: present
  - name: get the categories count
    ansible.builtin.command:  mongo --host mongodb.littlesimba.online --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
    register: product_count
  - name: load catalogue data
    ansible.builtin.command: mongo --host mongodb.littlesimba.online < /app/schema/catalogue.js
    when: product_count.stdout == "0" # keep double quotes

  - name: start and enable catalogue
    ansible.builtin.service:
      name: catalogue
      state: restarted
      enabled: yes