- name: user
  hosts: user
  become: yes
  tasks:
  - name: disabling old version of nodejs
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y
  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present
  - name: add roboshop user
    ansible.builtin.user:
      name: roboshop
  - name: Recursively remove app directory
    ansible.builtin.file:
      path: /app
      state: absent
  - name: create a directory
    ansible.builtin.file:
      path: /app
      state: directory
  - name: download the application
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/user.zip
      dest: /tmp
  - name: unzip application
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app 
      remote_src: yes
  - name: download dependencies
    ansible.builtin.command: npm install
    args:
      chdir: /app
  - name: copy user service
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service
  - name: deamon realod and start
    ansible.builtin.systemd_service:
      daemon_reload: true
  - name: Copy mongodb repo
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongodb.repo

  - name: Install mongodb client
    ansible.builtin.package:
      name: mongodb-org-shell
      state: present
  - name: get the users count
    ansible.builtin.command:  mongo --host mongodb.daws76s.online --quiet --eval 'db = db.getSiblingDB("users"); db.users.count()'
    register: user_count

  - name: load user data
    ansible.builtin.command: mongo --host mongodb.daws76s.online < /app/schema/user.js
    when: user_count.stdout == "0" # keep double quotes

  - name: start and enable user
    ansible.builtin.service:
      name: user
      state: restarted
      enabled: yes